### ISSUE TITLE
Post MME ASHG Event announcement

### ISSUE THREAD

**Issue by dazzariti** [MatchmakerExchange/matchmakerexchange.github.io#16]
Is there anyway to post this announcement about the ASHG session at the top of the MME page?  I've posted the text below of what we had in the email, will probably need to be abbreviated for the website.

JOIN MATCHMAKER EXCHANGE AT ASHG!
Matchmaker Exchange: Tools to Enable Gene Discovery
Building Evidence for Candidate Genes
October 7, 2015 - 7:00pm - 9:00pm
American Society of Human Genetics Annual Meeting
Baltimore Convention Center - Room 339
Baltimore, MD 

Join us to learn more about Matchmaker Exchange!
Introduction to Matchmaker Exchange - Participating Matchmaker Services - Matchmaker Exchange Success Story - How to Use the Matchmaker Exchange - Future of Matchmaker Exchange

OR ABBREVIATED TEXT:

JOIN MATCHMAKER EXCHANGE AT ASHG!
October 7, 2015 - 7:00pm - 9:00pm
Baltimore Convention Center - Room 339

**Comment by buske** [comment]
Here's what it looks like for me. Any thoughts, @dazzariti?

![untitled](https://cloud.githubusercontent.com/assets/4251264/9864530/9811830a-5b18-11e5-9351-3a4a8653f8bb.png)

**Comment by dazzariti** [comment]
@buske That looks great, thanks for turning that around so fast.

**Comment by buske** [comment]
@dazzariti Okay, that's now public. Let us know if you'd like it to link anywhere.
