### ISSUE TITLE
Update matchbox name on wheel

### ISSUE THREAD

**Issue by buske** [MatchmakerExchange/matchmakerexchange.github.io#31]

**Comment by Relequestual** [comment]
Why does it need to be in italics?

**Comment by buske** [comment]
From Danielle:
> the Broad system is _matchbox_ (all lowercase and italicized) – in the wheel it can just say _matchbox_ instead of Broad _matchbox_ since it is right next to the logo

**Comment by Relequestual** [comment]
That seems somewhat silly. Case I can understand... but like, what if I said DECIPHER now has to be underlined and bold?
It makes _matchbox_ look like we've made it stand out / alone for some reason, but without saying why.

**Comment by buske** [comment]
That's fair. I'm sure that branding choice was partly to make it stand out. If you'd like the MME website to only include un-styled titles for projects, I'd suggest having a chat with Danielle.
