### ISSUE TITLE
Add IRUD to "Participants" on homepage

### ISSUE THREAD

**Issue by dazzariti** [MatchmakerExchange/matchmakerexchange.github.io#37]
Pleas add "Initiative on Rare and Undiagnosed Diseases (IRUD)" with link to http://www.amed.go.jp/en/program/IRUD/ to Participants list on homepage per email below. 

From: Rehm, Heidi,Ph.D. 
Sent: Monday, March 06, 2017 10:20 PM
To: Boycott, Kym
Cc: Azzariti, Danielle R.
Subject: Re: AMED, Japan

Sounds good!

Sent from my iPhone

On Mar 6, 2017, at 8:57 PM, Boycott, Kym wrote:
Ok have clarified guys
 
I think we can add them under the section of interested folks and NOT to the wheel
 
Ahmed is the funder to not that logo but the IRUD logo is the group to add to the interested parties
 
They have not yet hooked data to MME and told them until they do that and I can see a link to search their data they don't get to be on the wheel (they have their own instance of Patient ARchive so it will be a direct link to them with keys etc).
 
K

**Comment by jxchong** [comment]
Seems to me that given the followup clarification from Kym, they aren't even a participant yet so there's no place to add them to the website at this point in time?

**Comment by dazzariti** [comment]
IRUD plans to join as a full member, closing this issue asking to add them to the Participant list
