### ISSUE TITLE
Updated Matching and Notification Table file

### ISSUE THREAD

**Issue by dazzariti** [MatchmakerExchange/matchmakerexchange.github.io#41]
Replace file here http://www.matchmakerexchange.org/assets/files/MME_Matching_Protocols_and_Notification_Method_2017-04-03.pdf with attached file - fixed a text wrapping issue and added Version date at bottom.

[MME Matching Protocols%2FNotification Method - Final.pdf](https://github.com/MatchmakerExchange/matchmakerexchange.github.io/files/894373/MME.Matching.Protocols.2FNotification.Method.-.Final.pdf)

**Comment by jxchong** [comment]
resolved by commit 6cede655ac73928b6539308aa7cd8cdfc508084f
