### ISSUE TITLE
Add Monarch and Genetic Alliance to the wheel

### ISSUE THREAD

**Issue by buske** [MatchmakerExchange/matchmakerexchange.github.io#5]

**Comment by dazzariti** [comment]
![monarch](https://cloud.githubusercontent.com/assets/10732982/8133028/9d49cc70-10f3-11e5-988b-61026c1306aa.png)

**Comment by dazzariti** [comment]
![genetic alliance](https://cloud.githubusercontent.com/assets/10732982/8133088/09b98eae-10f4-11e5-9e5f-0dc30137272c.png)
