### ISSUE TITLE
Homepage updates

### ISSUE THREAD

**Issue by buske** [MatchmakerExchange/matchmakerexchange.github.io#50]
https://www.youtube.com/watch?v=IDEhdzvlR4I

@dazzariti where do you think this should go on the website?

**Comment by dazzariti** [comment]
I don't know enough about web development to know if how much work this would be but...

Could we add a "Highlights from Matchmaker Exchange" column on either the right or left side of the homepage - we could embed the YouTube video, list the publications in our Bibliography, and if there's room embed our Twitter timeline

I attempt to draw it out here - 
https://docs.google.com/presentation/d/1mQsqNBLgXXH8c0Jn75NPgdoKQ_CGn8fUlPGdXTNXbG8/edit?usp=sharing

This code should work to embed the Twitter timeline but can be customized

<a class="twitter-timeline" data-width="400" data-height="300" data-dnt="true" href="https://twitter.com/MatchMExchange?ref_src=twsrc%5Etfw">Tweets by MatchMExchange</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by sgoehringer** [comment]
Twitter offers another tool to generate code and you can make some minor adjustments but you are somewhat restricted.  https://publish.twitter.com/#  The YouTube and other block wouldn't be a huge issue to include.

**Comment by Relequestual** [comment]
Doesn't look overly difficult.
I should be able to look at this in a few weeks time. If you've heard nothing by end Nov, please email me a reminder! =]

**Comment by Relequestual** [comment]
Because the site is responsive (works on desktop and mobile and ipad etc.), it's a little tricky to make use of the "white space" to the side of the main logo.

I have a few ideas how to handle this. I'll have a play and put some screenshots here to get feedback.

**Comment by Relequestual** [comment]
@dazzariti Do you have a list of publications with links that you would like?

**Comment by Relequestual** [comment]
@dazzariti Here is a preview for this:
https://relequestual.github.io/matchmakerexchange.github.io/
Try viewing it on desktop and mobile to see the difference.

I thought the video was rather important, so it is always shown, while publications and twitter feed are hidden by default on tablet and mobile.

I thought putting the "highlights" section as part of the main content would work better.

Let me know your feedback.

**Comment by dazzariti** [comment]
@Relequestual Great, this is looking good!  Should we show it on the MME call on Wednesday?

Some comments:

- Can you minimize the size of the graphic at the top of the page (four figures in grey box) so it doesn't take up so much room? We need it to be obvious a visitor should scroll down to learn more.

- Currently the "Exchange Participants" tab in the teal header directs to the wheel diagram on the homepage, would it be possible to add a "Highlights" tab that directs to the video/publications/Twitter feed?

- Publications can be found here -if you need this information in a different format just let me know
https://docs.google.com/spreadsheets/d/1U2kJnmx81I8JWnddzddTOFdSh9-L6F-zNsf4tjNMNio/edit?usp=sharing (2 tabs, Gene Discoveries and General Publications)

**Comment by dazzariti** [comment]
On November call, the group also discussed adding MME Statistics to the website

Here is the table that was discussed (with corrected numbers from DECIPHER)

[MME.Stats.Sept.2017.12.15.17.pptx](https://github.com/MatchmakerExchange/matchmakerexchange.github.io/files/1564116/MME.Stats.Sept.2017.12.15.17.pptx)

**Comment by Relequestual** [comment]
@dazzariti I can make those changes.

What information about the publications would you want to display? (I don't know).

Regarding the stats, I feel we should modify to "includes genes in small CNVs" as it's not all CNVs... there are some which would include LOADS of genes, and it would be silly to count those also. By small, I mean those which only overlap at most 2 genes, but that's more of a mouthful than "small".

**Comment by dazzariti** [comment]
@Relequestual I was looking for a way we could manage the citations that make it easy to add them to the website - would something like this work? https://blog.mendeley.com/2011/03/02/display-your-publications-on-your-own-website-using-exhibit/

**Comment by Relequestual** [comment]
@dazzariti sorry for the crazy long time in responding to this.
If you're happy with your ability to add and or modify the list now you've learnt some basics about making pull requests, we should move forward that way.

It looks possible to use BibBase and a Mendeley group to allow you to add publications to a group in Mendeley and have them automatically appear in a list. If that sounds preferable, let me know, and we can look at moving in that direction.
