### ISSUE TITLE
Update wheel image

### ISSUE THREAD

**Issue by dazzariti** [MatchmakerExchange/matchmakerexchange.github.io#56]
Sharon Plon requested the Baylor logo be updated on the wheel - perhaps we should hold this until we go forward with other requested updates to the wheel?
![bcmlogo](https://user-images.githubusercontent.com/10732982/33435950-8cdc9d9c-d5b1-11e7-9b53-fd82f28743d5.jpg)

**Comment by dazzariti** [comment]
Per discussion on November MME call - need to add "Knowledge Sources" to wheel as pictured.

Added PubCase Finder as a knowledge source, move Monarch Initiative from wheel to knowledge source

![mme 12 2f20 2f2017](https://user-images.githubusercontent.com/10732982/34015394-4b7eec74-e0ec-11e7-83e4-746562ba49a8.png)

**Comment by sdumitriu** [comment]
@dazzariti in the picture above, Monarch appears in two places. Is that intentional, or is it supposed to be removed from the wheel?

**Comment by dazzariti** [comment]
@sdumitriu Yes - thanks for checking. Monarch needs to be removed from the main wheel and only included under "Knowledge Sources"

**Comment by dazzariti** [comment]
Here are the summary of changes to the wheel discussed on the January MME call:

- Update Baylor logo 
- Move Monarch Initiative and PubMed Finder to a separate "Knowledge Sources" circle connected to main hub with dotted line
- Add IRUD to wheel - Initiative on Rare and Undiagnosed Diseases (logo attached)

MME Images Folder: https://drive.google.com/drive/folders/0B7YZGwsGAChyeWZfUHpPZEdYYTg?usp=sharing

[IRUD_Logo.pptx](https://github.com/MatchmakerExchange/matchmakerexchange.github.io/files/1664642/IRUD_Logo.pptx)
