### ISSUE TITLE
Update tables throughout website

### ISSUE THREAD

**Issue by dazzariti** [MatchmakerExchange/matchmakerexchange.github.io#59]
https://docs.google.com/spreadsheets/d/1WJ-NvW8_ifwcwmwntF9Xk4j10_-OQWRbWmLkLbvnSa0/edit?usp=sharing

This Google doc contains all the tables on the MME website and one new table with MME statistics. 

Cells highlighted in yellow contain new information and need to be updated on the website. 

If you have any questions or need this in another format just let me know. 

Thank you! Danielle

**Comment by Relequestual** [comment]
@dazzariti have you done this using other pull requests since creating this issue?
If so, we can close this issue.

**Comment by dazzariti** [comment]
Tables updated through other pull requests, closing this issue
