### ISSUE TITLE
Hyperlink the name in each of the circles to a webpage

### ISSUE THREAD

**Issue by buske** [MatchmakerExchange/matchmakerexchange.github.io#6]
*If possible.*
Should be possible using an image map.

**Comment by buske** [comment]
Here are URLs:
- ClinGenDB - http://clinicalgenome.org/
- GEM.app - https://genomics.med.miami.edu/
- PhenomeCentral - https://phenomecentral.org/
- Undiagnosed Diseases Program - http://www.genome.gov/27544402
- Cafe Variome - http://www.cafevariome.org/
- LOVD - http://www.lovd.nl/3.0/home
- DECIPHER - https://decipher.sanger.ac.uk/index
- GeneMatcher: https://genematcher.org/
- Monarch Initiative – http://monarchinitiative.org/
- PEER - http://www.geneticalliance.org/programs/biotrust/peer

**Comment by sdumitriu** [comment]
Or if that image becomes a scalable interactive SVG (won't work in IE <= 8 though).

**Comment by buske** [comment]
I tried using an SVG with embedding links, but the bitmap logos embedded within the SVG do not render nicely, at least on Firefox:

![image](https://cloud.githubusercontent.com/assets/4251264/9286203/f19483c4-42bc-11e5-8e97-bc87cae76def.png)
